### ISSUE TITLE
No longer able to enable/disable extensions via GNOME Tweaks or https://extensions.gnome.org/local/ since updating to latest version

### ISSUE THREAD

**Issue by ksze** [kazysmaster/gnome-shell-extension-lockkeys#67] opened 2020-02-06 02:35 UTC
OS: Ubuntu Desktop 18.04.3 x86-64

I updated the extension this morning and the extension can no longer be managed (toggled on or off) via either GNOME Tweaks or https://extensions.gnome.org/local/

GNOME Tweaks gives me a triangle-with-exclamation-mark icon, telling me "Error loading extension", and the toggle next to it is disabled. The only thing I can do from Tweaks is to open the extension's configuration dialog.

![image](https://user-images.githubusercontent.com/381556/73900925-23d65a00-48cc-11ea-96a8-f719b7ce760d.png)

The https://extensions.gnome.org/local/ website also shows me a red "ERROR" button next to the extension. I can open the extension's configuration dialog or completely uninstall it from the website.

![image](https://user-images.githubusercontent.com/381556/73900970-4ec0ae00-48cc-11ea-90ec-1a7d3e550fb6.png)

However, the extension seems to actually be in effect whenever I log on.

I have tried rebooting and reinstalling, to no avail.

**Comment by kazimierasvaina-cujo** [comment] 2020-02-06 11:30
Could you check the extension version ? 
cat ~/.local/share/gnome-shell/extensions/lockkeys@vaina.lt/metadata.json
Which version of Gnome are you using ?

**Comment by mzur** [comment] 2020-02-06 11:31
I can confirm this issue (extension version 30, GNOME 3.28.4). In the logfile, I get:
```
Extension "lockkeys@vaina.lt" had error: TypeError: actor is undefined
```
The extension seems to be working fine regardless.

**Comment by mzur** [comment] 2020-02-07 06:48
It works again after the most recent update and a restart of GNOME. Thanks!

**Comment by lastweakness** [comment] 2020-02-09 04:48
> It works again after the most recent update and a restart of GNOME. Thanks!

Please close the issue if it's already fixed.

**Comment by kazysmaster** [comment] 2020-02-09 16:35
Nice to hear.

**Closed by kazysmaster** 2020-02-09 16:35 UTC
